
#Machine Energy Storage Config. This config is synced from server to client.
[storage]
	#Base energy storage (Joules).
	enrichmentChamber = "800000"
	#Base energy storage (Joules).
	osmiumCompressor = "3200000"
	#Base energy storage (Joules).
	combiner = "1600000"
	#Base energy storage (Joules).
	crusher = "800000"
	#Base energy storage (Joules).
	metallurgicInfuser = "800000"
	#Base energy storage (Joules).
	purificationChamber = "3200000"
	#Base energy storage (Joules).
	energizedSmelter = "800000"
	#Base energy storage (Joules).
	digitalMiner = "1600000"
	#Base energy storage (Joules).
	electricPump = "1600000"
	#Base energy storage (Joules).
	chargePad = "20480000"
	#Base energy storage (Joules).
	rotaryCondensentrator = "800000"
	#Base energy storage (Joules).
	oxidationChamber = "3200000"
	#Base energy storage (Joules).
	chemicalInfuser = "3200000"
	#Base energy storage (Joules).
	chemicalInjectionChamber = "1600000"
	#Base energy storage (Joules).
	electrolyticSeparator = "1600000"
	#Base energy storage (Joules).
	precisionSawmill = "800000"
	#Base energy storage (Joules).
	chemicalDissolutionChamber = "1600000"
	#Base energy storage (Joules).
	chemicalWasher = "3200000"
	#Base energy storage (Joules).
	chemicalCrystallizer = "1600000"
	#Base energy storage (Joules).
	seismicVibrator = "800000"
	#Base energy storage (Joules).
	pressurizedReactionBase = "20000"
	#Base energy storage (Joules).
	fluidicPlenisher = "1600000"
	#Base energy storage (Joules).
	laser = "20000000"
	#Base energy storage (Joules).
	formulaicAssemblicator = "1600000"
	#Base energy storage (Joules).
	teleporter = "50000000"
	#Base energy storage (Joules).
	modificationStation = "1600000"
	#Base energy storage (Joules).
	isotopicCentrifuge = "3200000"
	#Base energy storage (Joules).
	nutritionalLiquifier = "1600000"
	#Base energy storage (Joules). Also defines max process rate.
	antiprotonicNucleosynthesizer = "10000000000"
	#Base energy storage (Joules).
	pigmentExtractor = "1600000"
	#Base energy storage (Joules).
	pigmentMixer = "3200000"
	#Base energy storage (Joules).
	paintingMachine = "1600000"
	#Base energy storage (Joules). Also defines max output rate.
	spsPort = "10000000000"

