onEvent('jei.add.items', e => {
    utils.listOf([
        'minecraft:dragon_egg',
        'minecraft:spawner',
        //Mekanism
        'mekanism:creative_fluid_tank',
        'mekanism:creative_chemical_tank',
        //AE2
        Item.of('appliedenergistics2:facade', '{item:"minecraft:stone"}'),
        //Structurize
        'structurize:plain_oak_oak_timber_frame',
        'structurize:double_crossed_oak_oak_timber_frame',
        'structurize:framed_oak_oak_timber_frame',
        'structurize:side_framed_oak_oak_timber_frame',
        'structurize:up_gated_oak_oak_timber_frame',
        'structurize:down_gated_oak_oak_timber_frame',
        'structurize:one_crossed_lr_oak_oak_timber_frame',
        'structurize:one_crossed_rl_oak_oak_timber_frame',
        'structurize:horizontal_plain_oak_oak_timber_frame',
        'structurize:side_framed_horizontal_oak_oak_timber_frame',
        'structurize:clay_oak_shingle',
        'structurize:clay_shingle_slab',
        'structurize:sceptergold',
        'structurize:shapetool',
        'structurize:sceptersteel',
        'structurize:sceptertag',
        'structurize:caliper',
        'structurize:blockcactusplank',
        'structurize:blockcactusslab',
        'structurize:blockcactusstair',
        'structurize:blockcactusfence',
        'structurize:blockcactusfencegate',
        'structurize:blockcactusdoor',
        'structurize:blockcactustrapdoor',
        'structurize:brown_bricks',
        'structurize:brown_brick_slab',
        'structurize:brown_brick_stairs',
        'structurize:brown_brick_wall',
        'structurize:beige_bricks',
        'structurize:beige_brick_slab',
        'structurize:beige_brick_stairs',
        'structurize:beige_brick_wall',
        'structurize:cream_bricks',
        'structurize:cream_brick_slab',
        'structurize:cream_brick_stairs',
        'structurize:cream_brick_wall',
        'structurize:brown_stone_bricks',
        'structurize:brown_stone_brick_slab',
        'structurize:brown_stone_brick_stairs',
        'structurize:brown_stone_brick_wall',
        'structurize:beige_stone_bricks',
        'structurize:beige_stone_brick_slab',
        'structurize:beige_stone_brick_stairs',
        'structurize:beige_stone_brick_wall',
        'structurize:cream_stone_bricks',
        'structurize:cream_stone_brick_slab',
        'structurize:cream_stone_brick_stairs',
        'structurize:cream_stone_brick_wall',
        'structurize:oak_blockpaperwall',
        //Tinker
        'tconstruct:tinker_station',
        'tconstruct:part_builder',
        Item.of('tconstruct:tinker_station', '{texture:"minecraft:oak_planks"}'),
        Item.of('tconstruct:part_builder', '{texture:"minecraft:oak_planks"}'),
        //TAC
        Item.of('minecraft:enchanted_book').enchant('tac:trigger_finger', 1),
        Item.of('minecraft:enchanted_book').enchant('tac:trigger_finger', 2),
        Item.of('minecraft:enchanted_book').enchant('tac:lightweight', 1),
        Item.of('minecraft:enchanted_book').enchant('tac:collateral', 1),
        Item.of('minecraft:enchanted_book').enchant('tac:over_capacity', 1),
        Item.of('minecraft:enchanted_book').enchant('tac:over_capacity', 2),
        Item.of('minecraft:enchanted_book').enchant('tac:over_capacity', 3),
        Item.of('minecraft:enchanted_book').enchant('tac:reclaimed', 1),
        Item.of('minecraft:enchanted_book').enchant('tac:reclaimed', 2),
        Item.of('minecraft:enchanted_book').enchant('tac:accelerator', 1),
        Item.of('minecraft:enchanted_book').enchant('tac:accelerator', 2),
        Item.of('minecraft:enchanted_book').enchant('tac:puncturing', 1),
        Item.of('minecraft:enchanted_book').enchant('tac:puncturing', 2),
        Item.of('minecraft:enchanted_book').enchant('tac:puncturing', 3),
        Item.of('minecraft:enchanted_book').enchant('tac:puncturing', 4),
        Item.of('minecraft:enchanted_book').enchant('tac:fire_starter', 1),
        'tac:workbench',
        'tac:nato_556_bullet',
        'tac:9mm_round',
        'tac:10_gauge_round',
        'tac:58x42',
        'tac:762x25',
        'tac:762x54',
        'tac:762x39',
        'tac:50bmg',
        'tac:rpg7_missile',
        'tac:coyote_sight',
        'tac:aimpoint_t1',
        'tac:eotech_n',
        'tac:vortex_uh_1',
        'tac:eotech_short',
        'tac:srs_red_dot',
        'tac:acog_4x_scope',
        'tac:qmk152',
        'tac:lpvo_1_6',
        'tac:8x_scope',
        'tac:old_8x_scope',
        'tac:old_4x_scope',
        'tac:mini_dot',
        'tac:micro_holo_sight',
        'tac:silencer',
        'tac:muzzle_brake',
        'tac:muzzle_compensator',
        'tac:pistol_silencer',
        'tac:light_stock',
        'tac:tactical_stock',
        'tac:weighted_stock',
        'tac:light_grip',
        'tac:specialised_grip',
        'tac:magnumround',
        'tac:round45',
        'tac:win_30-30',
        'tac:bullet_308',
        'chemlib:ingot_vanadium',
        'chemlib:ingot_tungsten',
        'chemlib:ingot_titanium',
        'chemlib:ingot_neodymium',
        'chemlib:ingot_magnesium',
        'chemlib:ingot_lithium',
        'chemlib:ingot_germanium',
        'chemlib:ingot_barium',
        'chemlib:ingot_chromium',
        'chemlib:ingot_thorium'
    ]).forEach(item => e.add(item))
})