onEvent('jei.remove.categories', e => {
    e.remove('minecraft:anvil')
    e.remove('jeresources:enchantment')
    e.remove('enchdesc:compatible_items')
    e.remove('minecraft:blasting')
    e.remove('minecraft:campfire')
    e.remove('minecraft:smoking')
    e.remove('industrialforegoing:fluid_extractor')
    e.remove('industrialforegoing:ore_fermenter')
    e.remove('industrialforegoing:ore_sieve')
    e.remove('industrialforegoing:ore_washer')
    e.remove('thermal:refinery')
    e.remove('thermal:tree_extractor')
    e.remove('powah:.coolant')
    e.remove('boss_tools:blastingfurnacecategory')
    e.remove('boss_tools:compressorcategory')
    e.remove('boss_tools:generatorcategory')
    e.remove('endless:extreme_craft')

})