
[Armor]
	#Enable Gold Upgraded Armor ?
	EnableGoldArmor = true
	#Enable Fire Upgraded Armor ?
	EnableFireArmor = true
	#Enable Ender Upgraded Armor ?
	EnableEnderArmor = true
	#Enable Water Upgraded Armor ?
	EnableWaterArmor = true
	#Enable Wither Upgraded Armor ?
	EnableWitherArmor = true
	#Enable Poison Upgraded Armor ?
	EnablePoisonArmor = true
	#Enable Phantom Upgraded Armor ?
	EnablePhantomArmor = true
	#Enable Feather Upgraded Armor ?
	EnableFeatherArmor = true
	#Enable Corrupt Upgraded Armor ?
	EnableCorruptArmor = true

	[Armor."Set Option"]
		#How many pieces of Gold Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerGoldArmorRequireSet = 3
		#How many pieces of Fire Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerFireArmorRequireSet = 3
		#How many pieces of Ender Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerEnderArmorRequireSet = 3
		#How many pieces of Water Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerWaterArmorRequireSet = 3
		#How many pieces of Wither Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerWitherArmorRequireSet = 3
		#How many pieces of Poison Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerPoisonArmorRequireSet = 3
		#How many pieces of Phantom Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerPhantomArmorRequireSet = 3
		#How many pieces of Feather Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerFeatherArmorRequireSet = 3