
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 633781
	#The name of the modpack
	modpackName = "Greed the Resource 4 - Infinity"
	#The version of the modpack
	modpackVersion = "V6.3"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

