
[Etc]
	#Void Rune's Damage
	#Range: 0 ~ 1000000
	Voidrunedamage = 10
	#Lava bomb's Radius
	#Range: 1 ~ 7
	Lavabombradius = 5
	#ScreenShake(on/off)
	"ScreenShake(on/off)" = true
	#BossMusic(on/off)
	"BossMusic(on/off)" = true

["Ender Guardian"]
	#EnderGuardian's DamageCap
	#Range: 0 ~ 1000000
	EnderGuardianDamageCap = 200
	#Ender guardian's block breaking ignore the MobGriefing
	EnderguardianBlockBreaking = true
	#ruined citadel spawn
	RuinedcitadelSpawn = true
	#Guardian's Immune to Long distance attack range.
	#Range: 1.0 ~ 1000000.0
	"Guardian's prevent attacks from far away Range" = 30.0
	#EnderGuardianBlockBreaking radius
	#Range: 0 ~ 20
	"EnderGuardianBlockBreaking X" = 15
	#EnderGuardianBlockBreaking radius
	#Range: 0 ~ 10
	"EnderGuardianBlockBreaking Y" = 2
	#EnderGuardianBlockBreaking radius
	#Range: 0 ~ 20
	"EnderGuardianBlockBreaking Z" = 15
	#EnderGuardian's Health Multiplier
	#Range: 0.0 ~ 1000000.0
	EnderGuardianHealthMultiplier = 15.0
	#EnderGuardian's Damage Multiplier
	#Range: 0.0 ~ 1000000.0
	EnderGuardianDamageMultiplier = 8.0

["Netherite Monstrosity"]
	#Monstrosity's Lavabomb magazine.
	#Range: 1 ~ 1000000
	LavabombMagazine = 5
	#Monstrosity's Lavabomb amount
	#Range: 1 ~ 1000000
	Lavabombamount = 5
	#Monstrosity's DamageCap
	#Range: 0 ~ 1000000
	MonstrosityDamageCap = 100
	#soul black smith spawn
	SoulblacksmithSpawn = true
	#Monstrosity's bodyBlocking verdict
	NetheritemonstrosityBodyBloking = true
	#Monstrosity's Immune to Long distance attack range.
	#Range: 1.0 ~ 1000000.0
	"Monstrosity's prevent attacks from far away Range" = 25.0
	#Monstrosity's Health Multiplier
	#Range: 0.0 ~ 1000000.0
	MonstrosityHealthMultiplier = 10.0
	#Monstrosity's Damage Multiplier
	#Range: 0.0 ~ 1000000.0
	MonstrosityDamageMultiplier = 5.0

["Ender Golem"]
	#Ender Golem's block breaking ignore the MobGriefing
	EndergolemBlockBreaking = false
	#Endergolem's Immune to Long distance attack range.
	#Range: 1.0 ~ 1000000.0
	"Endergolem's prevent attacks from far away Range" = 5.0
	#Golem's Health Multiplier
	#Range: 0.0 ~ 1000000.0
	GolemHealthMultiplier = 5.0
	#Golem's Damage Multiplier
	#Range: 0.0 ~ 1000000.0
	GolemDamageMultiplier = 3.5

[Ignis]
	#Ignis's Immune to Long distance attack range.
	#Range: 1.0 ~ 1000000.0
	"Ignis's prevent attacks from far away Range" = 100.0
	#Ignis's DamageCap
	#Range: 0 ~ 1000000
	IgnisDamageCap = 500
	#Ignis's Health Multiplier
	#Range: 0.0 ~ 1000000.0
	IgnisHealthMultiplier = 7.0
	#Ignis's Damage Multiplier
	#Range: 0.0 ~ 1000000.0
	IgnisDamageMultiplier = 3.0

