#Stop mods from adding custom flowers
flowers = true
#Stop mods from adding surface structures
surface_structures = false
#Stop mods from adding entities
entities = false
#Stop mods from adding lakes
lakes = false
#Stop mods air carvers
carvers_air = true
#Stop mods liquid carvers
carvers_liquid = true
#Play teleport sound when portal is used
play_sound = true

