
#Beginning of QuarryPlus configuration.
[common]
	#True to enable debug mode.
	debug = false
	#True to make machines work with no energy.
	NoEnergy = false
	#Amount of energy WorkbenchPlus can receive in a tick. [MJ]
	#Range: > 0
	WorkbenchMaxReceive = 25000
	#The amount of energy(FE) workbench receives in a tick.
	#Range: > 0
	WorkbenchTickBonus = 5000
	#Fasten quarry's head moving.
	FastQuarryHeadMove = false
	#True to enable ChunkDestroyer to collect bedrock as item if the machine has Bedrock Module in its module slots.
	CollectBedrock = false
	#DisableFrameChainBreak
	DisableFrameChainBreak = false
	#Set false to allow PumpPlus to remove non-source fluid block.
	RemoveOnlyFluidSource = false
	#True to enable RS control of machines.
	EnableRSControl = false
	#Range limit of ChunkDestroyer. set -1 to disable. The unit of number is `blocks`. 16 = 1 chunk.
	#Range: > -1
	QuarryRangeLimit = -1
	#Spawner Controller Blacklist
	spawnerBlacklist = ["minecraft:ender_dragon", "minecraft:wither", "minecraft:area_effect_cloud", "minecraft:item", "minecraft:player"]

	#Quarry PowerSetting [MJ] (min = 0, Max = 2,000,000,000 = 2 billion)
	[common.PowerSetting]

		[common.PowerSetting.Quarry]

			[common.PowerSetting.Quarry.BreakBlock]
				#Range: 0.0 ~ 2.0E9
				BasePower = 2000.0
				#Range: 0.0 ~ 2.0E9
				EfficiencyCoefficient = 1.3
				#Range: 0.0 ~ 2.0E9
				UnbreakingCoefficient = 1.0
				#Range: 0.0 ~ 2.0E9
				FortuneCoefficient = 1.3
				#Range: 0.0 ~ 2.0E9
				SilktouchCoefficient = 2.0
				#Range: 0.0 ~ 2.0E9
				BaseMaxReceive = 100000.0
				#Range: 0.0 ~ 2.0E9
				BaseMaxStored = 1000000.0

				[common.PowerSetting.Quarry.BreakBlock.MoveHead]
					#Range: 0.0 ~ 2.0E9
					BasePower = 200.0
					#Range: 0.0 ~ 2.0E9
					UnbreakingCoefficient = 1.0

			[common.PowerSetting.Quarry.MakeFrame]
				#Range: 0.0 ~ 2.0E9
				BasePower = 5000.0
				#Range: 0.0 ~ 2.0E9
				EfficiencyCoefficient = 1.3
				#Range: 0.0 ~ 2.0E9
				UnbreakingCoefficient = 1.0
				#Range: 0.0 ~ 2.0E9
				BaseMaxReceive = 100.0
				#Range: 0.0 ~ 2.0E9
				BaseMaxStored = 1000000.0

		[common.PowerSetting.Pump]

			[common.PowerSetting.Pump.DrainLiquid]
				#Range: 0.0 ~ 2.0E9
				BasePower = 500.0
				#Range: 0.0 ~ 2.0E9
				UnbreakingCoefficient = 1.0

			[common.PowerSetting.Pump.MakeFrame]
				#Range: 0.0 ~ 2.0E9
				BasePower = 500.0
				#Range: 0.0 ~ 2.0E9
				UnbreakingCoefficient = 1.0

		[common.PowerSetting.MiningWell]
			#Range: 0.0 ~ 2.0E9
			BasePower = 1000.0
			#Range: 0.0 ~ 2.0E9
			EfficiencyCoefficient = 1.3
			#Range: 0.0 ~ 2.0E9
			UnbreakingCoefficient = 1.0
			#Range: 0.0 ~ 2.0E9
			FortuneCoefficient = 1.3
			#Range: 0.0 ~ 2.0E9
			SilktouchCoefficient = 2.0
			#Range: 0.0 ~ 2.0E9
			BaseMaxReceive = 50000.0
			#Range: 0.0 ~ 2.0E9
			BaseMaxStored = 500000.0

		[common.PowerSetting.Laser]
			#Range: 0.0 ~ 2.0E9
			BasePower = 400.0
			#Range: 0.0 ~ 2.0E9
			EfficiencyCoefficient = 2.0
			#Range: 0.0 ~ 2.0E9
			UnbreakingCoefficient = 0.1
			#Range: 0.0 ~ 2.0E9
			FortuneCoefficient = 1.05
			#Range: 0.0 ~ 2.0E9
			SilktouchCoefficient = 1.1
			#Range: 0.0 ~ 2.0E9
			BaseMaxReceive = 50000.0
			#Range: 0.0 ~ 2.0E9
			BaseMaxStored = 500000.0

		[common.PowerSetting.Refinery]
			#Range: 0.0 ~ 2.0E9
			EfficiencyCoefficient = 1.2
			#Range: 0.0 ~ 2.0E9
			UnbreakingCoefficient = 1.0
			#Range: 0.0 ~ 2.0E9
			BaseMaxReceive = 6.0
			#Range: 0.0 ~ 2.0E9
			BaseMaxStored = 1000.0

	#Setting of enabling or disabling each machine. True to disable.
	[common.machines]
		MarkerPlus = false
		Replacer = true
		ExpPump = false
		NewQuarry = false
		QuarryPlus = true
		PumpPlus = false
		Placer = false
		MiningwellPlus = false
		AdvancedPump = false
		CreativeGenerator = false
		SolidFuelQuarry = false
		WorkbenchPlus = false
		EnchantMoverFromBook = true
		ChunkDestroyer = true
		MiniQuarry = false
		EnchantMover = false
		SpawnerController = true
		ModulePump = false
		ModuleExpPump = false
		ModuleReplacer = false
		ModuleTorch = false
		ModuleFuel = false
		ModuleRemoveBedrock = false

#Integration with other mods
[integration]
	#False to disable notification of chunk protection by FTBChunks
	SendNotificationOfChunkProtection = true

